[package]
name = "foresight"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hindsight-core = { path = "../hindsight-core" }

ethers = "2.0.7"
statistical = "1.0.0"
